# config.yaml

# --------------------------------------------------
# 1. User Credentials
# --------------------------------------------------
credentials:
  # Must be exactly "usernames" here
  usernames:
    test1:
      name: test1
      # Plain-text for now; will be hashed at runtime
      password: abc
    test2:
      name: test2
      password: abc
    # Add more users as needed:
    # charlie:
    #   name: Charlie Jones
    #   email: charlie@example.com
    #   password: charliepassword

# --------------------------------------------------
# 2. Cookie Settings
# --------------------------------------------------
cookie:
  # Name of the cookie in the browser
  name: survey_app_cookie
  # A secret key for signing the cookie (make this long & random!)
  key: your-very-secret-key-goes-here
  # How many days the login persists
  expiry_days: 180

