# config.yaml

credentials:
  usernames:
    tester1:
      email: tester1@example.com
      name: Tester One
      password: Password1!
    tester2:
      email: tester2@example.com
      name: Tester Two
      password: Password2!
    tester3:
      email: tester3@example.com
      name: Tester Three
      password: Password3!
    tester4:
      email: tester4@example.com
      name: Tester Four
      password: Password4!
    tester5:
      email: tester5@example.com
      name: Tester Five
      password: Password5!
    tester6:
      email: tester6@example.com
      name: Tester Six
      password: Password6!
    tester7:
      email: tester7@example.com
      name: Tester Seven
      password: Password7!
    tester8:
      email: tester8@example.com
      name: Tester Eight
      password: Password8!
    tester9:
      email: tester9@example.com
      name: Tester Nine
      password: Password9!
    tester10:
      email: tester10@example.com
      name: Tester Ten
      password: Password10!
cookie:
  name: survey_app_cookie
  key: your-very-secret-key-goes-here
  expiry_days: 180
preauthorized:
  emails: []
