credentials:
  usernames:
    tester1:
      email: tester1@example.com
      name: Test User One
      password: "password1" # Replace with a secure password
    tester2:
      email: tester2@example.com
      name: Test User Two
      password: "password2" # Replace with a secure password
    tester3:
      email: tester3@example.com
      name: Test User Three
      password: "password3" # Replace with a secure password
    tester4:
      email: tester4@example.com
      name: Test User Four
      password: "password4" # Replace with a secure password
    tester5:
      email: tester5@example.com
      name: Test User Five
      password: "password5" # Replace with a secure password
    tester6:
      email: tester6@example.com
      name: Test User Six
      password: "password6" # Replace with a secure password
    tester7:
      email: tester7@example.com
      name: Test User Seven
      password: "password7" # Replace with a secure password
    tester8:
      email: tester8@example.com
      name: Test User Eight
      password: "password8" # Replace with a secure password
    tester9:
      email: tester9@example.com
      name: Test User Nine
      password: "password9" # Replace with a secure password
    tester10:
      email: tester10@example.com
      name: Test User Ten
      password: "password10" # Replace with a secure password
cookie:
  expiry_days: 180
  key: "a_very_secret_key_please_change_it" # IMPORTANT: Change this to a random secret key
  name: "survey_app_cookie"
preauthorized: # Optional: Add emails of users who can register if registration is enabled (not in current script)
  emails:
    - tester1@example.com
    - tester2@example.com
